
Vagrant.configure("2") do |config|

  jenkins=[
    {
      :hostname => "jenkins",
      :box => "bento/ubuntu-18.04",
      :ip => "172.16.1.25",
      :ssh_port => "2200"
    }
  ]
  docker=[
    {
      :hostname => "docker1",
      :box => "bento/ubuntu-18.04",
      :ip => "172.16.1.26",
      :ssh_port => "2201"
    },
    {
      :hostname => "docker2",
      :box => "bento/ubuntu-18.04",
      :ip => "172.16.1.27",
      :ssh_port => "2202"
    }
  ]

  nginx_LB=[
    {
      :hostname => "loadbalencer1",
      :box => "bento/ubuntu-18.04",
      :ip => "172.16.1.28",
      :ssh_port => "2203"
    },
    {
      :hostname => "loadbalencer2",
      :box => "bento/ubuntu-18.04",
      :ip => "172.16.1.29",
      :ssh_port => "2204"
    }
  ]

  ansible=[
    {
      :hostname => "ansible",
      :box => "bento/ubuntu-18.04",
      :ip => "172.16.1.30",
      :ssh_port => "2205"
    }
  ]

  ansible.each do |machine|
    config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network :private_network, ip: machine[:ip]
            node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
            node.vm.provision "shell", path: "ansible_bootstrap.sh"
            node.vm.synced_folder "../data", "/home/vagrant"
            
            
            
            node.vm.provider :virtualbox do |vb|
              vb.customize ["modifyvm", :id, "--memory", 1024]
              vb.customize ["modifyvm", :id, "--cpus", 1]
            end
    end
  end


  jenkins.each do |machine|
    config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network :private_network, ip: machine[:ip]
            node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
            node.vm.provision "shell", path: "jenkins_bootstrap.sh"
            node.vm.synced_folder "../data", "/home/vagrant"
            
            
            
            node.vm.provider :virtualbox do |vb|
              vb.customize ["modifyvm", :id, "--memory", 1024]
              vb.customize ["modifyvm", :id, "--cpus", 1]
            end
    end
  end

  nginx_LB.each do |machine|
    config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network :private_network, ip: machine[:ip]
            node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
            node.vm.provision "shell", path: "nginx_LB.sh"
            node.vm.synced_folder "../data", "/home/vagrant"
            node.vm.provision "file" , source: "../data/nginx_lb/nginx_lb.conf", destination: "/etc/nginx/sites-available/default"
            node.vm.provision "shell", path: "nginx_restart.sh"
            
            
            
            node.vm.provider :virtualbox do |vb|
              vb.customize ["modifyvm", :id, "--memory", 1024]
              vb.customize ["modifyvm", :id, "--cpus", 1]
            end
    end
  end


  docker.each do |machine|
    config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network :private_network, ip: machine[:ip]
            node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
            node.vm.provision "shell", path: "docker_bootstrap.sh"
            # node.vm.synced_folder "../data/html", "/home/vagrant/html"
            node.vm.provision "file" , source: "../data/html/index.html", destination: "/home/vagrant/html/index.html"
            node.vm.provision "file" , source: "../data/docker/docker-compose.yml", destination: "/home/vagrant/docker-compose.yml"
            node.vm.provision "shell", path: "docker_compose.sh"


            
            
            
            node.vm.provider :virtualbox do |vb|
              vb.customize ["modifyvm", :id, "--memory", 1024]
              vb.customize ["modifyvm", :id, "--cpus", 1]
            end
    end
  end
end



