
Vagrant.configure("2") do |config|

  servers=[
    {
      :hostname => "Server1",
      :box => "bento/ubuntu-18.04",
      :ip => "172.16.1.25",
      :ssh_port => "2200"
    },
    {
      :hostname => "Server2",
      :box => "bento/ubuntu-18.04",
      :ip => "172.16.1.26",
      :ssh_port => "2201"
    },
    {
      :hostname => "Server3",
      :box => "bento/ubuntu-18.04",
      :ip => "172.16.1.27",
      :ssh_port => "2203"
    }
  ]

  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network :private_network, ip: machine[:ip]
            node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
            node.vm.provision "shell", path: "bootstrap.sh"
            node.vm.synced_folder "../data", "/var/www/html"
            
            
            
            node.vm.provider :virtualbox do |vb|
              vb.customize ["modifyvm", :id, "--memory", 1024]
              vb.customize ["modifyvm", :id, "--cpus", 2]
            end
    end
  end
end



